spring:
  jackson:
    date-format: yyyy-MM-dd
  application:
    name: sistema-lista-tarefa
  datasource:
      url: jdbc:mysql://localhost:3333/lista_tarefa?userTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      username: root
      password: admin
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
  threads:
      virtual:
        enabled: true

logging:
  level:
    dev.guilhermeluan: debug
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

endpoint:
  front: http://localhost:5500